fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    rbenv:  "git://github.com/justindowning/puppet-rbenv.git"
    git:    "git://github.com/puppetlabs/puppetlabs-git.git"
  symlinks:
    waylon: "#{source_dir}"
